# Este archivo contiene la configuración específica para el entorno de Integración Continua (CI).
# Se debe invocar explícitamente con: docker compose -f docker-compose.yml -f docker-compose.ci.yml ...
services:
  web:
    # Construye la imagen de Docker localmente usando el Dockerfile en el directorio actual.
    # Esto asegura que la CI pruebe los cambios más recientes del código.
    build: .
