# Generated by Django 5.2 on 2025-04-29 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_role_user_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("en_progreso", "En Progreso"),
                            ("en_revision", "En Revisión"),
                            ("radicado", "Radicado"),
                            ("finalizado", "Finalizado"),
                        ],
                        max_length=15,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process_type",
                    models.CharField(
                        choices=[
                            ("calculo_blindajes", "Cálculo de Blindajes"),
                            ("control_calidad", "Control de Calidad"),
                            ("asesoria", "Asesoría"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_final", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processes",
                        to="app.processstatus",
                    ),
                ),
                (
                    "process_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processes",
                        to="app.processtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("marca", models.CharField(blank=True, max_length=100, null=True)),
                ("modelo", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "serial",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "practica_asociada",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("fecha_adquisicion", models.DateField(blank=True, null=True)),
                ("fecha_vigencia_licencia", models.DateField(blank=True, null=True)),
                (
                    "fecha_ultimo_control_calidad",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "fecha_vencimiento_control_calidad",
                    models.DateField(blank=True, null=True),
                ),
                ("tiene_proceso_de_asesoria", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment",
                        to="app.process",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="report",
            name="process",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="app.process",
            ),
        ),
    ]
