# Generated by Django 5.2 on 2025-05-12 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_processstatus_processtype_process_equipment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="client_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("razon_social", models.CharField(max_length=255)),
                ("nit", models.CharField(max_length=20, unique=True)),
                (
                    "representante_legal",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("direccion_instalacion", models.CharField(max_length=255)),
                ("departamento", models.CharField(max_length=100)),
                ("municipio", models.CharField(max_length=100)),
                (
                    "persona_contacto",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="equipment",
            name="estado_actual",
            field=models.CharField(
                choices=[("en_uso", "En Uso"), ("dado_de_baja", "Dado de Baja")],
                default="en_uso",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="sede",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="estado_reporte",
            field=models.CharField(
                choices=[
                    ("en_generacion", "En Generación"),
                    ("revisado", "Revisado"),
                    ("aprobado", "Aprobado"),
                ],
                default="en_generacion",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="fecha_vencimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("cliente", "Cliente"),
                    ("gerente", "Gerente"),
                    ("director_tecnico", "Director Técnico"),
                    ("personal_tecnico_apoyo", "Personal Técnico de Apoyo"),
                    ("personal_administrativo", "Personal Administrativo"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
