# Generated by Django 5.2 on 2025-05-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_populate_permissions_for_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="estado",
            field=models.CharField(
                choices=[
                    ("en_progreso", "En Progreso"),
                    ("en_revision", "En Revisión"),
                    ("radicado", "Radicado"),
                    ("finalizado", "Finalizado"),
                ],
                default="en_progreso",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="process",
            name="process_type",
            field=models.CharField(
                choices=[
                    ("calculo_blindajes", "Cálculo de Blindajes"),
                    ("control_calidad", "Control de Calidad"),
                    ("asesoria", "Asesoría"),
                    ("otro", "Otro"),
                ],
                default="otro",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="ProcessStatus",
        ),
        migrations.DeleteModel(
            name="ProcessType",
        ),
    ]
