# Generated by Django 5.2 on 2025-05-23 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_anotacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="app.equipment",
            ),
        ),
        migrations.CreateModel(
            name="ProcessStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_anterior",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("en_progreso", "En Progreso"),
                            ("en_revision", "En Revisión"),
                            ("radicado", "Radicado"),
                            ("finalizado", "Finalizado"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Estado Anterior",
                    ),
                ),
                (
                    "estado_nuevo",
                    models.CharField(
                        choices=[
                            ("en_progreso", "En Progreso"),
                            ("en_revision", "En Revisión"),
                            ("radicado", "Radicado"),
                            ("finalizado", "Finalizado"),
                        ],
                        max_length=50,
                        verbose_name="Estado Nuevo",
                    ),
                ),
                (
                    "fecha_cambio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha del Cambio"
                    ),
                ),
                (
                    "proceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="app.process",
                        verbose_name="Proceso",
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="process_status_changes_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario que Modificó",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Estado de Proceso",
                "verbose_name_plural": "Logs de Estado de Procesos",
                "ordering": ["-fecha_cambio"],
            },
        ),
    ]
