# Generated by Django 5.2 on 2025-05-29 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_report_equipment_processstatuslog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="estado",
            field=models.CharField(
                choices=[
                    ("en_progreso", "En Progreso"),
                    ("en_revision", "En Revisión"),
                    ("radicado", "Radicado"),
                    ("finalizado", "Finalizado"),
                    ("en_modificacion", "En Modificación"),
                ],
                default="en_progreso",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="processstatuslog",
            name="estado_anterior",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en_progreso", "En Progreso"),
                    ("en_revision", "En Revisión"),
                    ("radicado", "Radicado"),
                    ("finalizado", "Finalizado"),
                    ("en_modificacion", "En Modificación"),
                ],
                max_length=50,
                null=True,
                verbose_name="Estado Anterior",
            ),
        ),
        migrations.AlterField(
            model_name="processstatuslog",
            name="estado_nuevo",
            field=models.CharField(
                choices=[
                    ("en_progreso", "En Progreso"),
                    ("en_revision", "En Revisión"),
                    ("radicado", "Radicado"),
                    ("finalizado", "Finalizado"),
                    ("en_modificacion", "En Modificación"),
                ],
                max_length=50,
                verbose_name="Estado Nuevo",
            ),
        ),
        migrations.CreateModel(
            name="ChecklistItemDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process_type",
                    models.CharField(
                        choices=[
                            ("calculo_blindajes", "Cálculo de Blindajes"),
                            ("control_calidad", "Control de Calidad"),
                            ("asesoria", "Asesoría"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Proceso",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nombre del Ítem"),
                ),
                ("order", models.PositiveIntegerField(verbose_name="Orden")),
                ("percentage", models.PositiveIntegerField(verbose_name="Porcentaje")),
            ],
            options={
                "verbose_name": "Definición de Ítem de Checklist",
                "verbose_name_plural": "Definiciones de Ítems de Checklist",
                "ordering": ["process_type", "order"],
                "unique_together": {
                    ("process_type", "name"),
                    ("process_type", "order"),
                },
            },
        ),
        migrations.CreateModel(
            name="ProcessChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Completado"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Completado"
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.checklistitemdefinition",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="app.process",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de Checklist de Proceso",
                "verbose_name_plural": "Ítems de Checklist de Proceso",
                "ordering": ["process", "definition__order"],
                "unique_together": {("process", "definition")},
            },
        ),
    ]
