# Generated by Django X.X on YYYY-MM-DD HH:MM
from django.db import migrations

# It's good practice to define these here or ensure they match your model's choices exactly
# For ProcessTypeChoices
CALCULO_BLINDAJES = "calculo_blindajes"
CONTROL_CALIDAD = "control_calidad"
# ASESORIA = "asesoria" # Not used in this population but good to be aware of
# OTRO = "otro" # Not used


def create_checklist_definitions(apps, schema_editor):
    ChecklistItemDefinition = apps.get_model("app", "ChecklistItemDefinition")

    # Definitions for Cálculo de Blindajes
    definitions_calculo = [
        {"name": "Elaboración de cálculo.", "order": 1, "percentage": 30},
        {"name": "Elaboración de informe.", "order": 2, "percentage": 30},
        {"name": "Revisión de informe.", "order": 3, "percentage": 20},
        {"name": "Publicación de informe.", "order": 4, "percentage": 20},
    ]
    for item_def in definitions_calculo:
        ChecklistItemDefinition.objects.get_or_create(
            process_type=CALCULO_BLINDAJES,
            name=item_def["name"],
            defaults={"order": item_def["order"], "percentage": item_def["percentage"]},
        )

    # Definitions for Control de Calidad
    definitions_control = [
        {"name": "Realización de medidas.", "order": 1, "percentage": 30},
        {"name": "Elaboración de informe.", "order": 2, "percentage": 30},
        {"name": "Revisión de informe.", "order": 3, "percentage": 20},
        {"name": "Publicación de informe", "order": 4, "percentage": 20},
    ]
    for item_def in definitions_control:
        ChecklistItemDefinition.objects.get_or_create(
            process_type=CONTROL_CALIDAD,
            name=item_def["name"],
            defaults={"order": item_def["order"], "percentage": item_def["percentage"]},
        )


def delete_checklist_definitions(apps, schema_editor):
    ChecklistItemDefinition = apps.get_model("app", "ChecklistItemDefinition")
    # This will delete all definitions created by this migration.
    # If you add more process types later, you might want to make this more specific.
    ChecklistItemDefinition.objects.filter(
        process_type__in=[CALCULO_BLINDAJES, CONTROL_CALIDAD]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "app",
            "0011_alter_process_estado_and_more",
        ),  # Depends on the migration that created the model
    ]

    operations = [
        migrations.RunPython(
            create_checklist_definitions, delete_checklist_definitions
        ),
    ]
