# Generated by Django 5.2 on 2025-06-05
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_checklistitemdefinition_practice_category_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="checklistitemdefinition",
            unique_together={
                ("process_type", "practice_category", "name"),
                ("process_type", "practice_category", "order"),
            },
        ),
        migrations.AlterOrderWithRespectTo(
            name="checklistitemdefinition",
            order_with_respect_to=None,
        ),
    ]
