# Generated by Django 5.2 on 2025-06-05 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_update_checklistitemdefinition_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checklistitemdefinition",
            options={
                "ordering": ["process_type", "practice_category", "order"],
                "verbose_name": "Definición de Ítem de Checklist",
                "verbose_name_plural": "Definiciones de Ítems de Checklist",
            },
        ),
    ]
