# Generated by Django 5.2 on 2025-06-18 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_correct_checklist_percentages"),
    ]

    operations = [
        migrations.AddField(
            model_name="process",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "roles__name__in": [
                        "gerente",
                        "director_tecnico",
                        "personal_tecnico_apoyo",
                    ]
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_processes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Asignado a",
            ),
        ),
        migrations.AddField(
            model_name="processchecklistitem",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_checklist_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="processchecklistitem",
            name="started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Inicio"
            ),
        ),
    ]
