# Generated by Django 5.2 on 2025-06-20 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_process_assigned_to_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialTuboRayosX",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=100, verbose_name="Marca")),
                ("modelo", models.CharField(max_length=100, verbose_name="Modelo")),
                ("serial", models.CharField(max_length=100, verbose_name="Serial")),
                ("fecha_cambio", models.DateField(verbose_name="Fecha de Cambio")),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_tubos_rayos_x",
                        to="app.equipment",
                        verbose_name="Equipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Tubo de Rayos X",
                "verbose_name_plural": "Historiales de Tubos de Rayos X",
                "ordering": ["-fecha_cambio"],
            },
        ),
    ]
