# Generated by Django 5.2 on 2025-06-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_historialtuborayosx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklistitemdefinition",
            name="practice_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("veterinaria", "Veterinaria"),
                    ("industrial", "Industrial"),
                    ("investigacion", "Investigación"),
                    ("medica_cat1", "Médica Categoría 1"),
                    ("medica_cat2", "Médica Categoría 2"),
                ],
                max_length=30,
                null=True,
                verbose_name="Categoría de Práctica",
            ),
        ),
        migrations.AlterField(
            model_name="process",
            name="practice_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("veterinaria", "Veterinaria"),
                    ("industrial", "Industrial"),
                    ("investigacion", "Investigación"),
                    ("medica_cat1", "Médica Categoría 1"),
                    ("medica_cat2", "Médica Categoría 2"),
                ],
                max_length=30,
                null=True,
                verbose_name="Categoría de Práctica",
            ),
        ),
    ]
