# Generated by Django 5.2 on 2025-07-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_update_process_and_checklist_definitions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklistitemdefinition",
            name="process_type",
            field=models.CharField(
                choices=[
                    ("calculo_blindajes", "Cálculo de Blindajes"),
                    ("control_calidad", "Control de Calidad"),
                    ("estudio_ambiental", "Estudio Ambiental"),
                    ("asesoria", "Asesoría"),
                    ("otro", "Otro"),
                ],
                max_length=20,
                verbose_name="Tipo de Proceso",
            ),
        ),
    ]
