# Generated by Django 5.2 on 2025-07-15 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_alter_checklistitemdefinition_process_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="processchecklistitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("en_progreso", "En Progreso"),
                    ("en_revision", "En Revisión"),
                    ("aprobado", "Aprobado"),
                    ("rechazado", "Rechazado"),
                ],
                default="pendiente",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.CreateModel(
            name="ChecklistItemStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_anterior",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_progreso", "En Progreso"),
                            ("en_revision", "En Revisión"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Estado Anterior",
                    ),
                ),
                (
                    "estado_nuevo",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_progreso", "En Progreso"),
                            ("en_revision", "En Revisión"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                        ],
                        max_length=20,
                        verbose_name="Estado Nuevo",
                    ),
                ),
                (
                    "fecha_cambio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha del Cambio"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="app.processchecklistitem",
                        verbose_name="Ítem del Checklist",
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checklist_item_status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario que Modificó",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Estado de Ítem de Checklist",
                "verbose_name_plural": "Logs de Estado de Ítems de Checklist",
                "ordering": ["-fecha_cambio"],
            },
        ),
    ]
