# Generated by Django 5.2 on 2025-07-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_processchecklistitem_status_checklistitemstatuslog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="estado",
            field=models.CharField(
                choices=[
                    ("en_progreso", "En Progreso"),
                    ("en_revision", "En Revisión"),
                    ("radicado", "Radicado"),
                    ("finalizado", "Finalizado"),
                    ("en_modificacion", "En Modificación"),
                    ("en_espera_administrativa", "En Espera Administrativa"),
                ],
                default="en_progreso",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="processstatuslog",
            name="estado_anterior",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en_progreso", "En Progreso"),
                    ("en_revision", "En Revisión"),
                    ("radicado", "Radicado"),
                    ("finalizado", "Finalizado"),
                    ("en_modificacion", "En Modificación"),
                    ("en_espera_administrativa", "En Espera Administrativa"),
                ],
                max_length=50,
                null=True,
                verbose_name="Estado Anterior",
            ),
        ),
        migrations.AlterField(
            model_name="processstatuslog",
            name="estado_nuevo",
            field=models.CharField(
                choices=[
                    ("en_progreso", "En Progreso"),
                    ("en_revision", "En Revisión"),
                    ("radicado", "Radicado"),
                    ("finalizado", "Finalizado"),
                    ("en_modificacion", "En Modificación"),
                    ("en_espera_administrativa", "En Espera Administrativa"),
                ],
                max_length=50,
                verbose_name="Estado Nuevo",
            ),
        ),
    ]
