# Generated by Django 5.2 on 2025-07-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_processchecklistitem_status_checklistitemstatuslog"),
    ]

    operations = [
        migrations.AddField(
            model_name="processchecklistitem",
            name="due_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha Límite"
            ),
        ),
    ]
