# Generated by Django 5.2 on 2025-07-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_processchecklistitem_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="estado_reporte",
            field=models.CharField(
                choices=[
                    ("en_generacion", "En Generación"),
                    ("revisado", "Revisado"),
                    ("aprobado", "Aprobado"),
                    ("requiere_correccion", "Requiere Corrección"),
                ],
                default="en_generacion",
                max_length=25,
            ),
        ),
    ]
