# Generated by Django 5.2 on 2025-07-18 00:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_alter_process_estado_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="process",
            name="assigned_to",
        ),
        migrations.AddField(
            model_name="process",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={
                    "roles__name__in": [
                        "gerente",
                        "director_tecnico",
                        "personal_tecnico_apoyo",
                    ]
                },
                related_name="assigned_processes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Asignado a",
            ),
        ),
    ]
