# Generated by Django 5.2 on 2025-07-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_remove_process_assigned_to_process_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processchecklistitem",
            name="completed_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Completado"
            ),
        ),
        migrations.AlterField(
            model_name="processchecklistitem",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Fecha Límite"),
        ),
        migrations.AlterField(
            model_name="processchecklistitem",
            name="started_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Inicio"
            ),
        ),
    ]
