# Generated by Django 5.2 on 2025-07-21 15:19

import app.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_alter_processchecklistitem_completed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="pdf_file",
            field=models.FileField(
                max_length=255,
                storage=app.storage.MockStorage(),
                upload_to="reports_pdfs/",
            ),
        ),
    ]
