# Generated by Django 5.2 on 2025-07-22 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_alter_report_pdf_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Equipo",
                "verbose_name_plural": "Tipos de Equipo",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="equipment",
            name="nombre",
            field=models.CharField(
                blank=True,
                help_text="Nombre específico o identificador del equipo si es necesario.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="equipment_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="equipments",
                to="app.equipmenttype",
                verbose_name="Tipo de Equipo",
            ),
        ),
    ]
