# Generated by Django 5.2 on 2025-07-23 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_populate_equipment_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientprofile",
            name="departamento",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="direccion_instalacion",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="municipio",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="persona_contacto",
        ),
        migrations.CreateModel(
            name="ClientBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej. Sede Central, Sede Norte…",
                        max_length=100,
                        verbose_name="Nombre de la Sede",
                    ),
                ),
                ("direccion_instalacion", models.CharField(max_length=255)),
                ("departamento", models.CharField(max_length=100)),
                ("municipio", models.CharField(max_length=100)),
                (
                    "persona_contacto",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="app.clientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sede de Cliente",
                "verbose_name_plural": "Sedes de Cliente",
            },
        ),
        migrations.AlterField(
            model_name="equipment",
            name="sede",
            field=models.ForeignKey(
                blank=True,
                help_text="Sede a la que pertenece este equipo",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipments",
                to="app.clientbranch",
                verbose_name="Sede de Cliente",
            ),
        ),
    ]
