# Generated by Django 5.2 on 2025-07-25 15:33

import app.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_remove_clientprofile_departamento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="pdf_file",
            field=models.FileField(
                max_length=255,
                storage=app.storage.PDFStorage(),
                upload_to="reports_pdfs/",
            ),
        ),
    ]
