# Generated by Django 5.2 on 2025-07-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_alter_report_pdf_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="process",
            name="fecha_asignacion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Asignación"
            ),
        ),
    ]
