# Generated by Django 5.2 on 2025-07-30 14:35

from django.db import migrations


def duplicate_checklist_definitions(apps, schema_editor):
    """Migrations to duplicate checklist definitions for 'niveles_de_referencia'.

    Duplicates checklist definitions from 'calculo_blindajes' and 'control_calidad'
    for the new 'niveles_de_referencia' process type.
    """
    ChecklistItemDefinition = apps.get_model("app", "ChecklistItemDefinition")

    # Valores de los tipos de proceso
    NIVELES_DE_REFERENCIA = "niveles_de_referencia"
    CALCULO_BLINDAJES = "calculo_blindajes"

    # Obtener todas las definiciones de los tipos de proceso a copiar
    definitions_to_copy = ChecklistItemDefinition.objects.filter(
        process_type__in=[CALCULO_BLINDAJES]
    ).order_by("process_type", "order")

    new_definitions = []
    for definition in definitions_to_copy:
        # Evitar duplicados si la migración se corre más de una vez
        if not ChecklistItemDefinition.objects.filter(
            process_type=NIVELES_DE_REFERENCIA, name=definition.name
        ).exists():
            new_def = ChecklistItemDefinition(
                process_type=NIVELES_DE_REFERENCIA,
                # No se copia practice_category ya que no aplica
                practice_category=None,
                name=definition.name,
                order=definition.order,
                percentage=definition.percentage,
            )
            new_definitions.append(new_def)

    if new_definitions:
        ChecklistItemDefinition.objects.bulk_create(new_definitions)


def reverse_duplicate_definitions(apps, schema_editor):
    """Delete the checklist definitions for 'niveles_de_referencia' when reversing the migration."""
    ChecklistItemDefinition = apps.get_model("app", "ChecklistItemDefinition")
    NIVELES_DE_REFERENCIA = "niveles_de_referencia"
    ChecklistItemDefinition.objects.filter(process_type=NIVELES_DE_REFERENCIA).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_alter_checklistitemdefinition_process_type_and_more"),
    ]

    operations = [
        migrations.RunPython(
            duplicate_checklist_definitions, reverse_code=reverse_duplicate_definitions
        ),
    ]
