name: Build & Push to ECR

on:
  push:
    branches:
      - feat/deploy-to-AWS

permissions:
  id-token: write    # allow OIDC token minting
  contents: read
  packages: write

env:
  ECR_REGISTRY: 978368259161.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: webserver
  IMAGE_TAG: ${{ github.ref_name }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::978368259161:role/GitHubActions-deploy-role
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry: ${{ env.ECR_REGISTRY }}

      - name: Build, tag & push image
        run: |
          docker build \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
