name: Build & Push to ECR

on:
  push:
    tags:
      - 'v*'

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 978368259161
  ECR_REPOSITORY: webserver
  IMAGE_TAG: ${{ github.ref_name }}

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS creds via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::978368259161:role/GitHubActions-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR

        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ env.AWS_ACCOUNT_ID }}

      - name: Build, tag & push
        run: |
          # define la URL completa usando las env que declaraste arriba
          ECR_REGISTRY=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
          SANITIZED_IMAGE_TAG=$(echo "${{ env.IMAGE_TAG }}" | sed 's/\//-/g')

          docker build \
            -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$SANITIZED_IMAGE_TAG \
            -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest .

          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }} --all-tags
