<<<<<<< HEAD
on:
  push:
    branches:
      - main

permissions:
  contents: write    # for version-bump commits & tags
  issues: write      # if you’re using @semantic-release/github comments
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
=======
release:
  name: Semantic Release
  needs: test-and-lint
  runs-on: ubuntu-latest
  if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  permissions:
    contents: write
    issues: write
    pull-requests: write

  steps:
    - name: Create GitHub App installation token
      id: app-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.CI_APP_PRIVATE_KEY }}

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
        token: ${{ steps.app-token.outputs.token }}

    - name: Configure Git user
      run: |
        git config user.name  "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "lts/*"

    - name: Install semantic-release and plugins
      run: |
        npm install -g semantic-release \
          @semantic-release/commit-analyzer \
          @semantic-release/release-notes-generator \
          @semantic-release/changelog \
          @semantic-release/git \
          @semantic-release/github

    - name: Run semantic-release
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      run: npx semantic-release
>>>>>>> 6bbcf97 (feat: add semantic release workflow test)
